services:
  - type: web
    name: media-converter-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    autoDeploy: true